pipeline {
  agent any
  tools { 
    nodejs 'nodeLTS_24130' // Jenkins > Global Tool Config: NodeJS named "nodeLTS_24130"
     allure 'allure' // Jenkins > Global Tool Config: Allure named "allure"
    }
    options {
    timeout(time: 20, unit: 'MINUTES') // To prevent running for long time 
  }
  // Binds TEST_CREDS_USR and TEST_CREDS_PSW
  environment { 
    TEST_CREDS = credentials('test-user')
    PLAYWRIGHT_BROWSERS_PATH = "${WORKSPACE}\\ms-playwright"
  }
  // -eu: shell safety setting (e -Exit immediately if any command fails; u- Treat unset variables as errors.)
  stages {
    stage('Build') {
      steps {
        bat '''
          npm ci
          npx playwright install
        '''
      }
    }
    stage('Test') {
      steps {
        bat '''
          set TEST_USER_NAME=%TEST_CREDS_USR%
          set TEST_PASSWORD=%TEST_CREDS_PSW%
          npm run demo
        '''
      }
      post {
        always {
         // Publish Allure results generated by the test run
          allure includeProperties: false,
                 jdk: '',
                 results: [[path: 'allure-results']],
                 reportBuildPolicy: 'ALWAYS'
        }
      }
    }
  }
}