pipeline {
  agent any
  tools { 
    nodejs 'nodeLTS_24130' // Jenkins > Global Tool Config: NodeJS named "nodeLTS_24130"
     allure 'allure' // Jenkins > Global Tool Config: Allure named "allure"
    }
    options {
    timeout(time: 20, unit: 'MINUTES') // To prevent running for long time 
  }
  // Binds TEST_CREDS_USR and TEST_CREDS_PSW
  environment { TEST_CREDS = credentials('test-user') }
  // -eu: shell safety setting (e -Exit immediately if any command fails; u- Treat unset variables as errors.)
  stages {
    stage('Build') {
      steps {
        sh '''
          set -eu 
          apt-get update
          apt-get install -y libglib2.0-0 libnss3 libatk1.0-0 libx11-xcb1 libxcomposite1 libxrandr2 libasound2 libatk-bridge2.0-0 libcups2 libgtk-3-0 fonts-liberation libgbm1 libpango-1.0-0 libpangocairo-1.0-0 libxdamage1 libxext6 libxfixes3
          npm ci
          npx playwright install
        '''
      }
    }
    stage('Test') {
      steps {
        sh '''
          export TEST_USER_NAME="$TEST_CREDS_USR"
          export TEST_PASSWORD="$TEST_CREDS_PSW"
          npm run demo
        '''
      }
      post {
        always {
         // Publish Allure results generated by the test run
          allure includeProperties: false,
                 jdk: '',
                 results: [[path: 'allure-results']],
                 reportBuildPolicy: 'ALWAYS'
        }
      }
    }
  }
}